### ISSUE TITLE
import instead of using

### ISSUE THREAD

**Issue by ablaom** [pebeto/MLJFlow.jl#1]
If these are the only methods you need, you can just use `import` here, right?

https://github.com/pebeto/MLJFlow.jl/blob/70e961e9244645b4dfc52a99eab06aea0852f0b1/src/MLJFlow.jl#L6

**Comment by pebeto** [comment]
Is not `using` and `import` the same thing in terms of functionality, just by the difference that `import` allows extending that certain functions?

**Comment by ablaom** [comment]
Yes you are right!
